### ISSUE TITLE
mbed-ls does not read mocks via import API create()

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/mbed-ls#120]
Identified while reviewing PR https://github.com/ARMmbed/greentea/pull/177
Issues faced https://github.com/ARMmbed/greentea/issues/180

Function ```mbedls_get_mocks()``` should be called from API function ```create()``` or from the original place where mock read code was refactored into this function.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2860

**Comment by mazimkhan** [comment]
Closing as Issue fixed.
