### ISSUE TITLE
Move 'lockfile' dependency to 'fasteners' or 'oslo.concurrency'

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-ls#130]
As mentioned at the top of the [lockfile documentation](https://pypi.python.org/pypi/lockfile/0.12.2), the package is now deprecated. It also a conflict with a default Ubuntu pip package as described here: https://github.com/ARMmbed/mbed-ls/issues/128#issuecomment-246587081

We can probably take care of both issues by moving to one of the recommended packages from the lockfile docs: [fasteners](https://pypi.python.org/pypi/fasteners) or [oslo.concurrency](http://docs.openstack.org/developer/oslo.concurrency/).

**Comment by mazimkhan** [comment]
@bridadan are you working  on it?

**Comment by bridadan** [comment]
@mazimkhan Not currently :smile:

**Comment by adbridge** [comment]
ARM Internal Ref: IOTSFW-2924

**Comment by mazimkhan** [comment]
Fixed by https://github.com/ARMmbed/mbed-ls/pull/139

**Comment by bridadan** [comment]
Thanks @mazimkhan !
