### ISSUE TITLE
support for NRF52840_DK

### ISSUE THREAD

**Issue by nvlsianpu** [ARMmbed/mbed-ls#160]
Nordic want to introduce nRF52840_DK port (http://www.nordicsemi.com/eng/Products/nRF52840-Preview-DK). mbed-os PR: https://github.com/ARMmbed/mbed-os/pull/3841. Interface firmware: (http://www.nordicsemi.com/eng/nordic/download_resource/60179/6/76665337). Reserved board ID <B>1102</B>.

**Comment by nvlsianpu** [comment]
@pan- @screamerbg

**Comment by theotherjimmy** [comment]
@nvlsianpu I'm closing this as #161 was merged.
