### ISSUE TITLE
ARM_BEETLE_SOC and ARM_MPS2_M0P are the same platform (id 5003)

### ISSUE THREAD

**Issue by fvincenzo** [ARMmbed/mbed-ls#168]
Please revert d3253bfc90ade5777c5d12cbeda5365570903e92 it breaks the support of Beetle in greentea.

ARM_BEETLE_SOC and ARM_MPS2_M0P are the same platform (id 5003)

@sg- @0xc0170

**Comment by sg-** [comment]
From the device database:
![image](https://cloud.githubusercontent.com/assets/496002/24503198/eb7e4e42-1548-11e7-9a02-eb288a29a05e.png)

@screamerbg

**Comment by theotherjimmy** [comment]
@sg- @fvincenzo @screamerbg I don't want these issues to just sit. Is this still a problem? if so, is there a workaround?

**Comment by theotherjimmy** [comment]
Closing with Sam's evidence that this is not a problem.
