### ISSUE TITLE
Print debugging information on STDERR

### ISSUE THREAD

**Issue by RomanSaveljev** [ARMmbed/mbed-ls#171]
Conventionally, programs print output not related to their main product on STDERR. Calling `mbedls --debug` prints debugging output on STDOUT.

In some situations (debugging) we want to see verbose output from mbedls that explains what is going on, yet use the list of the detected boards for something useful. STDIO separation is ought to provide for this feature.

**Comment by theotherjimmy** [comment]
@RomanSaveljev Would you like to submit a PR to do this?
