### ISSUE TITLE
Why is the Linux support Ubuntu specific?

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/mbed-ls#25]
The code seems pretty generic for linux, but maybe I missed something.

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSYST-476

**Comment by PrzemekWirkus** [comment]
Hi Johnny,
For Ubuntu Linux distro we have a proper port we've developed, we maintain and, test on our infrastructure.

Nothing stops us as a community from adding a new Linux distro support to mbed-ls's code base but we have to remember that we then have to commit to support and test. It is all about working software others can use seamlessly in the end.

We are still improving our infrastructure and this is why we are currently concentrating (and limiting) our efforts of limited number of supported platforms.

If anyone wants to port mbed-ls they can, and to verify their port they can use packages's unit tests:
```
$ git clone <mbed-ls>
$ cd mbed-ls
... Make your changes ...
$ python setup.py test
```

**Comment by jrobeson** [comment]
isn't it recommended to use udisks api on ubuntu instead of calling the programs directly?

**Comment by jrobeson** [comment]
that's another issue though. I will file that separately.

**Comment by PrzemekWirkus** [comment]
Cool, you are also more than welcome to send us pull request using udisks on Ubuntu to replace current implementation!

**Comment by PrzemekWirkus** [comment]
We have promising PR https://github.com/ARMmbed/mbed-ls/pull/26 to fix this issue.

**Comment by PrzemekWirkus** [comment]
LInux support was merged to master. We will have release soon! :)
