### ISSUE TITLE
Warning for incorrect MBED.HTM format says it can't read the file

### ISSUE THREAD

**Issue by theotherjimmy** [ARMmbed/mbed-ls#252]
This is clearly not true, and we should have a better warning.

Here's an example!

```
>mbedls
WARNING:root:Could not read htm on from usb id C006[Redacted]. Falling back to usb id
+---------------+----------------------+-------------+-------------+----------------+-----------------+
| platform_name | platform_name_unique | mount_point | serial_port |   target_id    | daplink_version |
+---------------+----------------------+-------------+-------------+----------------+-----------------+
|    VBLUNO51   |     VBLUNO51[0]      |      E:     |     COM8    | C006[Redacted] |       0244      |
+---------------+----------------------+-------------+-------------+----------------+-----------------+
```

```
>dir e:
[SNIP]
 Directory of E:\
03/22/2016  04:30 PM               280 MBED.HTM
03/22/2016  04:30 PM               384 DETAILS.TXT
[SNIP]
```

So the `WARNING:...` line should say something about invalid format... MBED.HTM... Falling back to usb id.

@yennster @bridadan This was the other minor issue we saw offline.

**Comment by bridadan** [comment]
Thanks for logging this, I think this would be a really great to feature to have, especially for people bringing up new platforms.

We should definitely to have this in either the major 2.x.x release or a minor release in the meantime.

**Comment by theotherjimmy** [comment]
I was thinking 1.3.4. Is that not going to work with semver?

**Comment by bridadan** [comment]
It'd be ok in 1.3.4 if you want, but if you wanted to focus on critical fixes only I'd say this is lower on the priority list.

**Comment by theotherjimmy** [comment]
That's a good point, if I did not already have an implementation.

**Comment by bridadan** [comment]
That works too :P

**Comment by theotherjimmy** [comment]
It's like +2/-2 to make this change. I debug statement upgraded to warning, and one warning rewritten.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-480

**Comment by theotherjimmy** [comment]
Implementation is already in.
