### ISSUE TITLE
Targets not detected on Windows 7

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-ls#264]
Latest version of mbedls (1.3.3) doesn't detect targets (K64, ST Disco) on Windows 7.

Downgrading to 1.3.1 works ok.

@theotherjimmy

**Comment by MarceloSalazar** [comment]
I guess is related to this https://github.com/ARMmbed/mbed-ls/issues/263

**Comment by bridadan** [comment]
@MarceloSalazar Yes most likely, since the change happened in 1.3.2. I'll be putting up a patch to fix this momentarily, thanks for your patience.

**Comment by theotherjimmy** [comment]
Thanks Brian. This has been released for a while.
