### ISSUE TITLE
CircleCi - active but failing

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-ls#29]
An example from the latest PR, which just adds a new target, the CI fails - https://circleci.com/gh/ARMmbed/mbed-ls/76

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSYST-575

**Comment by PrzemekWirkus** [comment]
It fails because OS on CircleCI instance is not detected by mbed-ls.
This will be soon fixed with Generic Linux support via one of the existing external PRs.

**Comment by PrzemekWirkus** [comment]
Fixed with https://github.com/ARMmbed/mbed-ls/pull/26
