### ISSUE TITLE
mbedls does not list JLINK mcus

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbed-ls#32]
In Mac OS X and Linux mbedls does not list targets that have a JLINK firmware interface rather than the MBED one.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-620

**Comment by PrzemekWirkus** [comment]
Andres, can you give example of the device which is not enumerated by mbed-ls so I can reproduce?

**Comment by PrzemekWirkus** [comment]
I will close this, no more feedback from OP.
