### ISSUE TITLE
Indicating about ASSERT.TXT

### ISSUE THREAD

**Issue by jupe** [ARMmbed/mbed-ls#336]
In CI we need to know if interface asserts and ASSERT.TXT appears to mount point. Would be optimal solution if mbed-ls could indicate if ASSERT.TXT file exists when list boards. mbed-ls could e.g. read that file when it exists and include it in board json, or just report all files in mount point so that application could read them when needed. This would help to avoid using bad state boards in CI.

**Comment by bridadan** [comment]
Thanks for raising this @jupe.

This information is already present, we just aren't adding it to the JSON blob. The data can be accessed here: https://github.com/ARMmbed/mbed-ls/blob/master/mbed_lstools/lstools_base.py#L212

**Comment by jupe** [comment]
Any change to add available files to JSON blob - in CLI interface ?

**Comment by bridadan** [comment]
Not at this time. If I get time to patch #352 today I'll add this as well in a different PR.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-476
