### ISSUE TITLE
Update setup.py maintenance info

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-ls#343]
No disrespect to Mr. Wirkus, Mr. Seferidis, and Mr. Crosby, but I think its safe to say they don't maintain this package anymore. Can this be updated without breaking anything?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-474

**Comment by theotherjimmy** [comment]
@bridadan I think that's a safe change.
