### ISSUE TITLE
No support for Scilab EFM32 Pearl Gecko boards since 1.4

### ISSUE THREAD

**Issue by EmbedEngineer** [ARMmbed/mbed-ls#355]
Since the 1.4 verson is requiring a DETAILS.txt file, apperently boards with an older DAPLink version such as the EFM32 Pearl Gecko board are not supported any more. Is there any possibility for implementing a workaround apart from downgrading mbed-ls to 1.3?

**Comment by bridadan** [comment]
Thanks for raising the issue. I think we may have just caught this bug in #352 (though it only talks about mbed.htm in that issue). My latest PR #353 should fix it if you'd like to test it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-471

**Comment by EmbedEngineer** [comment]
@bridadan Thank you. Your #353 fixes the problem.
