### ISSUE TITLE
Can't detect target with JLink 8.0

### ISSUE THREAD

**Issue by OmerRosler** [ARMmbed/mbed-ls#360]
We are using the newest JLink commander software and fail to detect our connected board.

The device is JLink plus:
![Device](http://kamami.com/4973-thickbox_default/segger-j-link-plus-80828.jpg)
We use this connection for flashing during debugging and directly from the command line, but fail the detection in mbed-ls.

`mbedls --debug` output:

DEBUG:mbedls.main:mbed-ls ver. 1.4.5
DEBUG:mbedls.main:host: ('nt', 'Windows', '7', '6.1.7601', 'win32')
DEBUG:mbedls.lstools_win7:_iter_vals <PyHKEY object at 0x026C87D70>
DEBUG:mbedls.lstools_win7:Fetching mounted devices from disk service registry entry
DEBUG:mbedls.lstools_win7:_iter_vals <PyHKEY object at 0x026C8D70>
DEBUG:mbedls.lstools_win7:Fetching usb storage devices from USBSTOR service registry entry
DEBUG:mbedls.lstools_win7:No USBSTOR service found, no device can be detected
DEBUG:mbedls.lstools_win7:target_id_usb_id -> mount_point mapping: {}
DEBUG:mbedls.lstools_base:Candidates for display []
DEBUG:mbedls.main:Return code: 0

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-970

**Comment by bridadan** [comment]
Hi @OmerRosler. Mbed LS currently doesn't support external debuggers "out of the box". The JLink detection functionality only works for development boards with the specific JLink firmware flashed to the board's interface chip.

**Comment by bridadan** [comment]
Closing this for now since this would require a significant rewrite of mbed-ls to accomplish this.
