### ISSUE TITLE
API to get supported platforms names

### ISSUE THREAD

**Issue by jupe** [ARMmbed/mbed-ls#365]
Current only way to fetch all supported target names are like this:

```
mbeds = mbed_lstools.create()
db_items = list(mbeds.plat_db.items())
supported_targets = sorted([i[1]["platform_name"] for i in db_items])
```

Like you see it's not very simple and clear way. I would like to have dedicated public API to achieve same, eg `mbeds.get_supported_targets()` which could do these tricks for me.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1187
