### ISSUE TITLE
How to distinguish between two MCUs with same DAPLink firmware

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-ls#388]
We have a new target (RTL8710AF), which is programmed using RTL8195AM development board. It flashes fine. However, mbedls shows the same target_id prefix (4600) regardless whether we connect 8195 or 8710. How are we supposed to distinguish between these MCUs? It flashes both these targets fine.

We cannot use Greentea now, because it cannot detect which MCU is there. Is this something that mbedls should handle?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1577

**Comment by bridadan** [comment]
Hi @janjongboom, you can use the "mock" feature of mbed-ls to tell greentea what the board actually is: https://github.com/ARMmbed/mbed-ls#mocking-renaming-platforms

**Comment by janjongboom** [comment]
@bridadan Yes, I know how to get around it, but I want an upstream fix.

**Comment by bridadan** [comment]
@janjongboom Can you help me understand your hardware setup a bit more? Is it that the RTL8195AM board has been populated with a RTL8710AF module now? If so, have you updated the DAPLink firmware on the board with the new target id? If the new platform has a new target id, you can submit it to mbed-ls by following these steps: https://github.com/ARMmbed/mbed-ls#adding-support-for-daplink-compatible-platforms-daplink-st-link-and-cmsis-dap

**Comment by janjongboom** [comment]
@bridadan Yes, RTL8915AM dev board with 8710AF module. But there's no updated DAPLink for it. The same DAPLink can program both chips; thus it has the same ID.

**Comment by bridadan** [comment]
@janjongboom thanks for clarifying. We can't detect which MCU is "behind" the DAPLink with mbed-ls, so we rely on the DAPLink firmware exposing the proper target ID. If you want mbed-ls to detect the changed MCU/module, you'll need to get a very slightly modified version of the DAPLink firmware with the changed target ID.

**Comment by bridadan** [comment]
As a slight clarification, it's possible to ship the same DAPLink firmware for both boards, yet at run time expose the correct target ID depending on the connected MCU (this is done already for the Nordic NRF5x boards: https://github.com/ARMmbed/DAPLink/blob/master/source/board/mkit_dk_dongle_nrf5x.c#L54). But either way, some modifications to the DAPLink firmware will be necessary.
