### ISSUE TITLE
Serial number regex not allowing non-hex characters

### ISSUE THREAD

**Issue by mvolstad** [ARMmbed/mbed-ls#41]
The USB serial number search limits the range to 0-9 and A-F. 
Atmel EDBG device serial numbers contains the preample ATML. This is excluded from the search and therefore the COM-port detection does not work. 

Proposal for fix in:
https://github.com/mvolstad/mbed-ls/tree/serialnumber_regex_fix

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-775

**Comment by PrzemekWirkus** [comment]
Actually it is not USB serial number but we are searching for ```target id``` of mbed-enabled device. Which is a ASCII hex string. The problem with board you have might be with the way we parse whole USB ID. I need to deeper into that.
