### ISSUE TITLE
"0224" not added in platform database

### ISSUE THREAD

**Issue by Hoohaha** [ARMmbed/mbed-ls#412]
Could someone help to add 0224 for NXP frdmk28f board.

I got an warning from the CLI:

WARNING:mbedls.lstools_base:daplink entry: "0224" not found in platform database

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-390*

**Comment by bridadan** [comment]
Hi @Hoohaha, it doesn't look like this target is supported by Mbed OS, may I ask what is your use case?

**Comment by Hoohaha** [comment]
We use mbedls to get to know boards information(id, serial port, disk) which are already connected to host PC, than we can control or test the boards with these information. Mbed Ls saved time to manual configure some configuration.

**Comment by bridadan** [comment]
As stated in #412, closing.
