### ISSUE TITLE
Redefine COM port for a target

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-ls#48]
It might be useful to redirect COM port for a target.

 For instance,I would like to use ftdi chip for instance to redirect serial (bypass interface chip), to narrow down the variables in play when having an issue with uart.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-802

**Comment by PrzemekWirkus** [comment]
TODO: 
* Still need to test with few platforms and different configurations.
* Missing ```README.md``` entry regarding this feature.

**Comment by PrzemekWirkus** [comment]
@0xc0170 Martin, I've added this new feature so you can override ```mbed-ls``` results with a ```mbedls.json``` file, see attached to this Issue PR.
Please close it if you think it is OK for you to use it.
