### ISSUE TITLE
Unmounted MBEDs are not listed

### ISSUE THREAD

**Issue by justbuchanan** [ARMmbed/mbed-ls#56]
Right now on Linux, mbedls only shows MBEDs that are mounted to the filesystem.  It would be helpful if these were shown even if the mount point is blank.  This is especially useful for Linux distros that don't mount USB devices by default.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2146

**Comment by theotherjimmy** [comment]
I just merged #197 Clasing.
