### ISSUE TITLE
Add ID for Unlisted boards

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-ls#75]
## Problem
There are going to be boards that use DAPLink but are not part of the mbed-enabled program, these boards should have a known 'unknown' identifier that is used so they do not gank up the system. 

## Solution
Add a known 'Unknown Board' ID, I suggest using `OSHW`. 
https://github.com/ARMmbed/mbed-ls/blob/master/mbed_lstools/lstools_base.py

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2521

**Comment by PrzemekWirkus** [comment]
@BlackstoneEngineering Can you provide before and after mbedls printouts please?

**Comment by BlackstoneEngineering** [comment]
Closing this issue, see https://github.com/ARMmbed/mbed-ls/pull/76
