### ISSUE TITLE
mock needs to be global

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-ls#99]
## Problem
When using the `--mock` subcommand it creates a folder in what ever directory I am in, I then must use that mocked target from within that folder. This use case makes sense as a backend tool but not as a user facing tool.

## Solution
When adding a 'mocked` device it should be added globally by default with the option to be folder specific for when needed on the backend. This reflects the transition of this tool from a backend tool to a frontend user facing tool. 

## Common Use Case
A user wants to test their new platform, to do this they must run the tests from the mbedmicro/mbed/tools directory. All of these tools require the board to be usable from mbedls. Thus the user runs `mbedls --mock=xxxx:PlatformName` and then the user can run the tests and validate their port. Under the current model the user would have to run all the tests from the base folder where they start the mock, but if you're doing active SDK development then this doesnt make sense as your prompt will be all over the place. Makes much more sense to add it globally so the mocked platform can be used by any tool / test anywhere on the local system.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2738

**Comment by PrzemekWirkus** [comment]
Mock can be global only per OS user. Do you think this would be enough?

**Comment by BlackstoneEngineering** [comment]
Yes, that should be good enough, for the typical users (windows, single user laptop/desktop machine) this should net the same effect.

**Comment by PrzemekWirkus** [comment]
Done via #106

**Comment by BlackstoneEngineering** [comment]
cool, closing issue
